from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

from .mcp.config import load_config
from .mcp.server import create_server


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="playwright-python-mcp")
    parser.add_argument(
        "--allowed-hosts",
        nargs="+",
        help="Comma-separated list of hosts this server is allowed to serve from.",
    )
    parser.add_argument("--allowed-origins", help="Semicolon-separated browser request origin allowlist.")
    parser.add_argument("--allow-unrestricted-file-access", action="store_true")
    parser.add_argument("--blocked-origins", help="Semicolon-separated browser request origin blocklist.")
    parser.add_argument("--block-service-workers", action="store_true")
    parser.add_argument(
        "--browser",
        default="chrome",
        help="Browser or channel to use. Initial implementation defaults to chrome.",
    )
    parser.add_argument(
        "--caps",
        default="",
        help="Comma-separated list of additional capabilities to enable.",
    )
    parser.add_argument(
        "--cdp-endpoint",
        "--cdp",
        dest="cdp_endpoint",
        help="CDP endpoint to connect to.",
    )
    parser.add_argument("--channel", dest="channel", help="Browser channel alias for --browser.")
    parser.add_argument("--cdp-header", action="append", help="CDP header, e.g. 'Authorization: Bearer token'.")
    parser.add_argument("--cdp-timeout", type=int, help="Timeout in milliseconds for connecting to CDP endpoint.")
    parser.add_argument(
        "--codegen",
        choices=("python", "none"),
        help='Language to use for generated code snippets. This port supports "python" or "none".',
    )
    parser.add_argument(
        "--config",
        help="Path to a JSON configuration file.",
    )
    parser.add_argument(
        "--headless",
        action="store_true",
        help="Run the browser in headless mode.",
    )
    parser.add_argument(
        "--test-id-attribute",
        default="data-testid",
        help="Attribute name to use for test ids.",
    )
    parser.add_argument(
        "--console-level",
        choices=("error", "warning", "info", "debug"),
        help='Level of console messages to include in snapshot event logs. Defaults to "info".',
    )
    parser.add_argument(
        "--endpoint",
        help="Bound browser endpoint to connect to.",
    )
    parser.add_argument("--executable-path", help="Path to browser executable.")
    parser.add_argument("--extension", action="store_true")
    parser.add_argument("--grant-permissions", help="Comma-separated permissions to grant.")
    parser.add_argument("--host", help="Host to bind server to.")
    parser.add_argument("--ignore-https-errors", action="store_true")
    parser.add_argument("--init-page", action="append", help="Python port records this config value; JS init pages are not executed.")
    parser.add_argument("--init-script", action="append", help="Path to JavaScript file to add as an initialization script.")
    parser.add_argument("--isolated", action="store_true")
    parser.add_argument("--image-responses", choices=("allow", "omit"))
    parser.add_argument("--no-sandbox", dest="sandbox", action="store_false")
    parser.add_argument("--sandbox", dest="sandbox", action="store_true")
    parser.set_defaults(sandbox=None)
    parser.add_argument(
        "--output-dir",
        help="Directory for files generated by tools.",
    )
    parser.add_argument("--output-max-size", type=int)
    parser.add_argument(
        "--output-mode",
        choices=("file", "stdout"),
        help='Whether to return text artifacts inline or by file reference. Can be "file" or "stdout".',
    )
    parser.add_argument("--port", type=int, help="Port to listen on for HTTP/SSE transport.")
    parser.add_argument("--proxy-bypass", help="Comma-separated proxy bypass domains.")
    parser.add_argument("--proxy-server", help="Proxy server URL.")
    parser.add_argument("--remote-header", action="append", help="Header to send to --endpoint connections.")
    parser.add_argument("--save-session", action="store_true")
    parser.add_argument("--secrets", help="Path to dotenv file containing secrets.")
    parser.add_argument("--shared-browser-context", action="store_true")
    parser.add_argument("--snapshot-mode", choices=("full", "none"))
    parser.add_argument("--storage-state", help="Path to storage state file.")
    parser.add_argument("--timeout", type=int, help="Alias for --timeout-action.")
    parser.add_argument("--timeout-action", type=int)
    parser.add_argument("--timeout-navigation", type=int)
    parser.add_argument("--user-agent")
    parser.add_argument("--user-data-dir")
    parser.add_argument("--viewport-size", help='Viewport size, for example "1280x720".')
    parser.add_argument(
        "--vision",
        action="store_true",
        help="Legacy option, use --caps=vision instead.",
    )

    subparsers = parser.add_subparsers(dest="command")
    install_parser = subparsers.add_parser(
        "install-browser",
        help="Install Playwright browser dependencies.",
    )
    install_parser.add_argument("browsers", nargs="*")
    return parser


def main(argv: list[str] | None = None) -> None:
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.command == "install-browser":
        cmd = [sys.executable, "-m", "playwright", "install", *args.browsers]
        raise SystemExit(subprocess.call(cmd))

    config = load_config(
        browser=args.channel or args.browser,
        caps=args.caps,
        config_path=Path(args.config) if args.config else None,
        headless=args.headless,
        test_id_attribute=args.test_id_attribute,
        vision=args.vision,
        console_level=args.console_level,
        output_dir=Path(args.output_dir) if args.output_dir else None,
        allowed_hosts=_split_comma_values(args.allowed_hosts),
        allowed_origins=_split_semicolon(args.allowed_origins),
        allow_unrestricted_file_access=args.allow_unrestricted_file_access or None,
        blocked_origins=_split_semicolon(args.blocked_origins),
        block_service_workers=args.block_service_workers or None,
        cdp_endpoint=args.cdp_endpoint,
        cdp_header=_headers(args.cdp_header),
        cdp_timeout=args.cdp_timeout,
        codegen=args.codegen,
        endpoint=args.endpoint,
        executable_path=args.executable_path,
        extension=args.extension or None,
        grant_permissions=_split_comma(args.grant_permissions),
        host=args.host,
        ignore_https_errors=args.ignore_https_errors or None,
        init_page=args.init_page,
        init_script=args.init_script,
        isolated=args.isolated or None,
        image_responses=args.image_responses,
        output_max_size=args.output_max_size,
        output_mode=args.output_mode,
        port=args.port,
        proxy_bypass=args.proxy_bypass,
        proxy_server=args.proxy_server,
        remote_header=_headers(args.remote_header),
        sandbox=args.sandbox,
        save_session=args.save_session or None,
        secrets=_dotenv(Path(args.secrets)) if args.secrets else None,
        shared_browser_context=args.shared_browser_context or None,
        snapshot_mode=args.snapshot_mode,
        storage_state=args.storage_state,
        timeout=args.timeout,
        timeout_action=args.timeout_action,
        timeout_navigation=args.timeout_navigation,
        user_agent=args.user_agent,
        user_data_dir=args.user_data_dir,
        viewport_size=_resolution(args.viewport_size),
    )
    server = create_server(config)
    server.run()


def _split_comma(value: str | None) -> list[str] | None:
    return [item.strip() for item in value.split(",") if item.strip()] if value else None


def _split_comma_values(values: list[str] | None) -> list[str] | None:
    if not values:
        return None
    result: list[str] = []
    for value in values:
        result.extend(_split_comma(value) or [])
    return result


def _split_semicolon(value: str | None) -> list[str] | None:
    return [item.strip() for item in value.split(";") if item.strip()] if value else None


def _headers(values: list[str] | None) -> dict[str, str] | None:
    if not values:
        return None
    result: dict[str, str] = {}
    for value in values:
        name, _, header_value = value.partition(":")
        result[name.strip()] = header_value.strip()
    return result


def _resolution(value: str | None) -> dict[str, int] | None:
    if not value:
        return None
    delimiter = "x" if "x" in value else ","
    width, height = (int(part) for part in value.split(delimiter, 1))
    return {"width": width, "height": height}


def _dotenv(path: Path) -> dict[str, str]:
    result: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        result[key.strip()] = value.strip().strip("\"'")
    return result
